const gulp = require('gulp');
const path = require('path');
const fs = require('fs/promises');
const xml2js = require('xml2js');
const { glob } = require('glob');
function stripIndent(str) {
    const match = str.match(/^[ \t]*(?=\S)/mg);
    if (!match) return str;
    const indent = Math.min(...match.map(m => m.length));
    return indent > 0 ? str.replace(new RegExp(`^[ \\t]{${indent}}`, 'mg'), '') : str;
}

const THINGWORX_DIR = (() => {
    const idx = process.argv.indexOf('--dir');
    if (idx !== -1 && process.argv[idx + 1]) return path.resolve(process.argv[idx + 1]);
    const eq = process.argv.find(a => a.startsWith('--dir='));
    if (eq) return path.resolve(eq.slice(6));
    return path.join(__dirname, 'WindchillClients', 'ThingWorx');
})();
const TARGET_FOLDERS = ['Mashups', 'Things', 'ThingShapes', 'ThingTemplates'];

// Helper to discover projects
async function discoverProjects(projectFilter) {
    const allProjects = [];
    const dirs = await fs.readdir(THINGWORX_DIR, { withFileTypes: true });

    for (const dirent of dirs) {
        if (!dirent.isDirectory()) continue;
        const dirName = dirent.name;

        // Skip if not included in projectFilter (unless 'All')
        if (projectFilter.toLowerCase() !== 'all' && !projectFilter.split(',').map(s => s.trim()).includes(dirName)) {
            continue;
        }

        // Check for prefixed subfolders
        const projectPath = path.join(THINGWORX_DIR, dirName);
        try {
            const subDirs = await fs.readdir(projectPath, { withFileTypes: true });
            for (const sub of subDirs) {
                if (sub.isDirectory() && sub.name !== 'Code' && sub.name !== 'node_modules') {
                    // This subfolder might contain Things/Mashups
                    const subFolderPath = path.join(projectPath, sub.name);
                    allProjects.push({
                        projectName: dirName,
                        projectDir: projectPath,
                        prefixedDir: subFolderPath
                    });
                    break; // only need the first valid prefixed subfolder per project based on structure
                }
            }
        } catch (e) {
            // ignore
        }
    }
    return allProjects;
}

// Flatten mashup widgets
function flattenWidgets(widget, list = []) {
    if (!widget || typeof widget !== 'object') return list;
    list.push(widget);

    if (widget.Widgets && Array.isArray(widget.Widgets)) {
        widget.Widgets.forEach(w => flattenWidgets(w, list));
    }
    return list;
}

// Ensure directory exists
async function ensureDir(dirPath) {
    await fs.mkdir(dirPath, { recursive: true });
}

function getArg(envName, flagName) {
    if (process.env[envName]) return process.env[envName];
    const idx = process.argv.indexOf(`--${flagName}`);
    if (idx > -1 && process.argv.length > idx + 1) return process.argv[idx + 1];
    const eqArg = process.argv.find(a => a.startsWith(`--${flagName}=`));
    if (eqArg) return eqArg.split('=')[1];
    return null;
}

// Verbose helper: check `--verbose`, `npm_config_verbose`, or `VERBOSE` env
function isVerbose() {
    // Accept: --verbose (standalone), --verbose=true, npm_config_verbose, or VERBOSE env
    if (process.argv.includes('--verbose')) return true;
    const eq = process.argv.find(a => a.startsWith('--verbose='));
    if (eq) {
        const v = eq.split('=')[1];
        if (v === undefined || v === null) return true;
        return ['1', 'true', 'yes'].includes(String(v).toLowerCase());
    }
    const val = getArg('npm_config_verbose', 'verbose') || process.env.VERBOSE;
    if (val === undefined || val === null) return false;
    if (typeof val === 'string') return ['1', 'true', 'yes'].includes(val.toLowerCase());
    return Boolean(val);
}

function vLog(...args) {
    if (isVerbose()) console.log(...args);
}

// ---- DataShape → TypeScript extraction ----

const TWX_TYPES_CONTENT = `/**
 * ThingWorx Base Type Mappings
 * Auto-generated by extract-services — do not edit manually
 */

/** ThingWorx Location type */
export interface TwxLocation {
    latitude: number;
    longitude: number;
    elevation?: number;
}

/** ThingWorx InfoTable — a typed array of rows matching a DataShape */
export type InfoTable<T = Record<string, unknown>> = T[];

/** Map of ThingWorx baseType names to TypeScript types */
export type TwxBaseTypeMap = {
    STRING: string;
    NUMBER: number;
    INTEGER: number;
    LONG: number;
    BOOLEAN: boolean;
    DATETIME: Date;
    JSON: Record<string, unknown>;
    XML: string;
    INFOTABLE: InfoTable;
    HYPERLINK: string;
    IMAGELINK: string;
    HTML: string;
    TEXT: string;
    TAGS: string[];
    LOCATION: TwxLocation;
    THINGNAME: string;
    MASHUPNAME: string;
    DATASHAPENAME: string;
    QUERY: Record<string, unknown>;
    IMAGE: string;
    BLOB: Blob;
    NOTHING: void;
};
`;

const KNOWN_TWX_BASE_TYPES = new Set([
    'STRING', 'NUMBER', 'INTEGER', 'LONG', 'BOOLEAN', 'DATETIME', 'JSON', 'XML',
    'INFOTABLE', 'HYPERLINK', 'IMAGELINK', 'HTML', 'TEXT', 'TAGS', 'LOCATION',
    'THINGNAME', 'MASHUPNAME', 'DATASHAPENAME', 'QUERY', 'IMAGE', 'BLOB', 'NOTHING',
]);

/** Strip dots and hyphens to produce a valid TypeScript identifier. */
function dsNameToInterfaceName(dsName) {
    return dsName.replace(/[.\-]/g, '');
}

/** Returns true if the name requires quoting as a TypeScript property key. */
function needsQuoting(name) {
    return !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

async function extractDataShapes(proj) {
    const dataShapesDir = path.join(proj.prefixedDir, 'DataShapes');
    try {
        await fs.access(dataShapesDir);
    } catch {
        return; // no DataShapes folder for this project
    }

    const xmlFiles = await glob(`${dataShapesDir.replace(/\\/g, '/')}/*.xml`, { nodir: true });
    if (xmlFiles.length === 0) return;

    const codeDir = path.join(proj.projectDir, 'Code', 'DataShapes');
    await ensureDir(codeDir);

    // Write the shared ThingWorx type definitions file
    await fs.writeFile(path.join(codeDir, 'twx-types.ts'), TWX_TYPES_CONTENT, 'utf8');
    vLog('Wrote twx-types.ts');

    const exportLines = ["export * from './twx-types';"];

    for (const xmlFile of xmlFiles) {
        const fileContent = await fs.readFile(xmlFile, 'utf8');
        const parsed = await xml2js.parseStringPromise(fileContent);

        const dataShapes = parsed.Entities?.DataShapes?.[0]?.DataShape;
        if (!dataShapes) continue;

        for (const ds of dataShapes) {
            const dsName = ds.$.name;
            const description = ds.$.description || '';
            const baseDataShapeName = ds.$.baseDataShape || '';
            const fields = ds.FieldDefinitions?.[0]?.FieldDefinition || [];

            // Sort fields by ordinal
            const sortedFields = [...fields].sort(
                (a, b) => parseInt(a.$.ordinal, 10) - parseInt(b.$.ordinal, 10)
            );

            const interfaceName = dsNameToInterfaceName(dsName);

            // Detect typed INFOTABLE fields (need InfoTable<T> import)
            const hasInfoTableRef = sortedFields.some(
                f => f.$.baseType === 'INFOTABLE' && f.$['aspect.dataShape']
            );

            // Build import line
            let tsContent = hasInfoTableRef
                ? "import type { TwxBaseTypeMap, InfoTable } from './twx-types';\n"
                : "import type { TwxBaseTypeMap } from './twx-types';\n";

            // Import base DataShape for interface inheritance
            let baseInterfaceName = '';
            if (baseDataShapeName) {
                baseInterfaceName = dsNameToInterfaceName(baseDataShapeName);
                tsContent += `import type { ${baseInterfaceName} } from './${baseDataShapeName}';\n`;
            }

            // Import any DataShapes referenced by INFOTABLE fields
            const infotableRefs = new Map();
            for (const field of sortedFields) {
                if (field.$.baseType === 'INFOTABLE' && field.$['aspect.dataShape']) {
                    const refDs = field.$['aspect.dataShape'];
                    infotableRefs.set(refDs, dsNameToInterfaceName(refDs));
                }
            }
            for (const [refDs, refInterface] of infotableRefs) {
                tsContent += `import type { ${refInterface} } from './${refDs}';\n`;
            }

            tsContent += '\n';

            // Interface JSDoc
            tsContent += `/**\n * DataShape: ${dsName}\n`;
            if (description) tsContent += ` * ${description}\n`;
            tsContent += ` * Auto-generated from ${path.basename(xmlFile)} — do not edit manually\n */\n`;

            // Interface declaration (with optional inheritance)
            tsContent += baseInterfaceName
                ? `export interface ${interfaceName} extends ${baseInterfaceName} {\n`
                : `export interface ${interfaceName} {\n`;

            for (const field of sortedFields) {
                const fieldName = field.$.name;
                const baseType = field.$.baseType;
                const isPK = field.$['aspect.isPrimaryKey'] === 'true';
                const fieldDesc = field.$.description || '';
                const ordinal = field.$.ordinal;
                const refDataShape = field.$['aspect.dataShape'];

                // Field JSDoc
                const docParts = [];
                if (fieldDesc) docParts.push(fieldDesc);
                if (isPK) docParts.push('@primaryKey');
                docParts.push(`@ordinal ${ordinal}`);
                tsContent += `    /** ${docParts.join(' | ')} */\n`;

                // Resolve TypeScript type
                let tsType;
                if (baseType === 'INFOTABLE' && refDataShape) {
                    tsType = `InfoTable<${dsNameToInterfaceName(refDataShape)}>`;
                } else if (KNOWN_TWX_BASE_TYPES.has(baseType)) {
                    tsType = `TwxBaseTypeMap['${baseType}']`;
                } else {
                    tsType = `unknown /* TODO: unknown baseType '${baseType}' */`;
                }

                const quotedName = needsQuoting(fieldName) ? `'${fieldName}'` : fieldName;
                tsContent += `    ${quotedName}: ${tsType};\n`;
            }

            tsContent += '}\n';

            const fileName = `${dsName}.ts`;
            await fs.writeFile(path.join(codeDir, fileName), tsContent, 'utf8');
            vLog('Wrote DataShape TS:', path.join(codeDir, fileName));
            exportLines.push(`export * from './${dsName}';`);
        }
    }

    // Barrel index.ts
    const indexContent = '// Auto-generated — do not edit manually\n' + exportLines.join('\n') + '\n';
    await fs.writeFile(path.join(codeDir, 'index.ts'), indexContent, 'utf8');
    console.log(`Extracted ${exportLines.length - 1} DataShape(s) → ${codeDir}`);
}

async function extractServicesTask() {
    const projectArg = getArg('npm_config_project', 'project') || 'All';
    console.log(`Extracting services for project(s): ${projectArg}`);
    const projects = await discoverProjects(projectArg);
    vLog('Discovered projects:', projects.map(p => p.projectName));

    for (const proj of projects) {
        const codeDir = path.join(proj.projectDir, 'Code');

        // Clean Code/ directory
        await fs.rm(codeDir, { recursive: true, force: true }).catch(() => { });

        for (const targetFolder of TARGET_FOLDERS) {
            const targetDirPath = path.join(proj.prefixedDir, targetFolder);
            try {
                await fs.access(targetDirPath);
            } catch (e) {
                continue; // folder doesn't exist, skip
            }

            const xmlFiles = await glob(`${targetDirPath.replace(/\\/g, '/')}/*.xml`, { nodir: true });
            vLog(`Found ${xmlFiles.length} xml files in ${targetDirPath}`);

            for (const xmlFile of xmlFiles) {
                const fileContent = await fs.readFile(xmlFile, 'utf8');
                const parsed = await xml2js.parseStringPromise(fileContent);

                let entityNodes = [];
                let entityType = '';

                if (targetFolder === 'Things' && parsed.Entities?.Things?.[0]?.Thing) {
                    entityNodes = parsed.Entities.Things[0].Thing;
                    entityType = 'Things';
                } else if (targetFolder === 'ThingShapes' && parsed.Entities?.ThingShapes?.[0]?.ThingShape) {
                    entityNodes = parsed.Entities.ThingShapes[0].ThingShape;
                    entityType = 'ThingShapes';
                } else if (targetFolder === 'ThingTemplates' && parsed.Entities?.ThingTemplates?.[0]?.ThingTemplate) {
                    entityNodes = parsed.Entities.ThingTemplates[0].ThingTemplate;
                    entityType = 'ThingTemplates';
                } else if (targetFolder === 'Mashups' && parsed.Entities?.Mashups?.[0]?.Mashup) {
                    entityNodes = parsed.Entities.Mashups[0].Mashup;
                    entityType = 'Mashups';
                }

                for (const entity of entityNodes) {
                    const entityName = entity.$.name;
                    const entityCodeDir = path.join(codeDir, entityType, entityName);

                    if (['Things', 'ThingShapes', 'ThingTemplates'].includes(entityType)) {
                        // ServiceImplementations could be directly under entity or inside ThingShape node for Thing Templates
                        let shapeNodes = [entity];
                        if (entity.ThingShape && Array.isArray(entity.ThingShape)) {
                            shapeNodes.push(...entity.ThingShape);
                        }

                        for (const shape of shapeNodes) {
                            if (shape.ServiceImplementations && shape.ServiceImplementations[0] && shape.ServiceImplementations[0].ServiceImplementation) {
                                for (const svc of shape.ServiceImplementations[0].ServiceImplementation) {
                                    const svcName = svc.$.name;
                                    if (svc.ConfigurationTables && svc.ConfigurationTables[0].ConfigurationTable) {
                                        for (const ct of svc.ConfigurationTables[0].ConfigurationTable) {
                                            if (ct.Rows && ct.Rows[0].Row && ct.Rows[0].Row[0]) {
                                                const row = ct.Rows[0].Row[0];
                                                if (row.code && row.code[0]) {
                                                    await ensureDir(entityCodeDir);
                                                    await fs.writeFile(path.join(entityCodeDir, `${svcName}.js`), stripIndent(row.code[0]).trim() + '\n', 'utf8');
                                                        vLog('Wrote service JS:', path.join(entityCodeDir, `${svcName}.js`));
                                                } else if (row.sql && row.sql[0]) {
                                                    await ensureDir(entityCodeDir);
                                                    await fs.writeFile(path.join(entityCodeDir, `${svcName}.sql`), stripIndent(row.sql[0]).trim() + '\n', 'utf8');
                                                        vLog('Wrote service SQL:', path.join(entityCodeDir, `${svcName}.sql`));
                                                }
                                            }
                                        }
                                    }
                                }
                            }

                            if (shape.Subscriptions && shape.Subscriptions[0] && shape.Subscriptions[0].Subscription) {
                                for (const sub of shape.Subscriptions[0].Subscription) {
                                    if (sub.ServiceImplementation && sub.ServiceImplementation[0]) {
                                        const svcName = sub.ServiceImplementation[0].$.name;
                                        const subCodeDir = path.join(entityCodeDir, 'Subscriptions');
                                        const svc = sub.ServiceImplementation[0];
                                        if (svc.ConfigurationTables && svc.ConfigurationTables[0].ConfigurationTable) {
                                            for (const ct of svc.ConfigurationTables[0].ConfigurationTable) {
                                                if (ct.Rows && ct.Rows[0].Row && ct.Rows[0].Row[0]) {
                                                    const row = ct.Rows[0].Row[0];
                                                    if (row.code && row.code[0]) {
                                                        await ensureDir(subCodeDir);
                                                        await fs.writeFile(path.join(subCodeDir, `${svcName}.js`), stripIndent(row.code[0]).trim() + '\n', 'utf8');
                                                        vLog('Wrote subscription JS:', path.join(subCodeDir, `${svcName}.js`));
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } else if (entityType === 'Mashups') {
                        if (entity.mashupContent && entity.mashupContent[0]) {
                            try {
                                // The mashup content is inside CDATA but xml2js parses it as a string
                                const mashupData = JSON.parse(entity.mashupContent[0].trim());

                                // Extract CSS
                                if (mashupData.CustomMashupCss && mashupData.CustomMashupCss.trim() !== '') {
                                    await ensureDir(entityCodeDir);
                                    await fs.writeFile(path.join(entityCodeDir, 'stylesheet.css'), mashupData.CustomMashupCss, 'utf8');
                                    vLog('Wrote mashup stylesheet:', path.join(entityCodeDir, 'stylesheet.css'));
                                }

                                // Extract Widgets
                                if (mashupData.UI && mashupData.UI.Widgets) {
                                    const allWidgets = flattenWidgets(mashupData.UI);
                                    for (const widget of allWidgets) {
                                        if (!widget.Properties) continue;

                                        const type = (widget.Properties.Type || '').toLowerCase();
                                        const id = widget.Properties.Id;

                                        if (type === 'expression2' || type === 'validator2') {
                                            if (widget.Properties.Expression) {
                                                const displayName = widget.Properties.DisplayName || id;
                                                await ensureDir(entityCodeDir);
                                                await fs.writeFile(path.join(entityCodeDir, `${displayName}.js`), widget.Properties.Expression, 'utf8');
                                                vLog('Wrote widget expression:', path.join(entityCodeDir, `${displayName}.js`));
                                            }
                                        } else if (type === 'htmltextarea') {
                                            if (widget.Properties.Text) {
                                                await ensureDir(entityCodeDir);
                                                await fs.writeFile(path.join(entityCodeDir, `${id}.html`), widget.Properties.Text, 'utf8');
                                                vLog('Wrote widget html:', path.join(entityCodeDir, `${id}.html`));
                                            }
                                        }
                                    }
                                }
                            } catch (e) {
                                console.error(`Failed to parse mashupContent for ${entityName}`, e);
                            }
                        }
                    }
                }
            }
        }

        // Extract DataShapes → TypeScript interfaces
        await extractDataShapes(proj);
    }
}

async function embedServicesTask() {
    const fileFilterArgs = process.env.EMBED_FILES || getArg('npm_config_files', 'files') || getArg('npm_config_only', 'only');
    let fileFilters = [];
    if (fileFilterArgs) {
        fileFilters = fileFilterArgs.split(',').map(s => s.trim().replace(/\\/g, '/'));
    }

    if (fileFilters.length > 0) {
        console.log(`Filtering for files: ${fileFilters.join(', ')}`);
        vLog('Verbose: file filters:', fileFilters);
    }

    const projects = await discoverProjects('All');
    vLog('Verbose: embedding into projects:', projects.map(p => p.projectName));

    for (const proj of projects) {
        const codeDir = path.join(proj.projectDir, 'Code');
        try {
            await fs.access(codeDir);
        } catch {
            continue; // No Code dir for this project
        }

        const allCodeFiles = await glob(`${codeDir.replace(/\\/g, '/')}/**/*.*`, { nodir: true });
        const changes = [];
        let reportObj = { generated: new Date().toISOString(), changes };
        vLog(`Found ${allCodeFiles.length} code files under ${codeDir}`);

        for (const codeFilePath of allCodeFiles) {
            if (codeFilePath.endsWith('embed-report.json')) continue;

            const relativePath = path.relative(codeDir, codeFilePath).replace(/\\/g, '/');

            // Filter check
            if (fileFilters.length > 0) {
                let match = false;
                for (const f of fileFilters) {
                    if (f.includes('/')) {
                        if (relativePath.endsWith(f)) match = true;
                    } else {
                        if (path.basename(relativePath) === f) match = true;
                    }
                }
                if (!match) continue;
            }

            const parts = relativePath.split('/');
            const assetType = parts[0];
            if (assetType === 'DataShapes') continue; // auto-generated TypeScript — not embeddable
            const entityName = parts[1];
            const fileName = path.basename(relativePath);
            const isSubscription = parts.includes('Subscriptions');

            const sourceXmlPath = path.join(proj.prefixedDir, assetType, `${entityName}.xml`);
            let actualXmlPath;
            const possibleXmls = await glob(`${path.join(proj.prefixedDir, assetType).replace(/\\/g, '/')}/*.xml`);
            for (const p of possibleXmls) {
                if (path.basename(p, '.xml').endsWith(entityName)) {
                    actualXmlPath = p;
                    break;
                }
            }

            if (!actualXmlPath) {
                console.warn(`Could not find source XML for ${relativePath}`);
                vLog('Could not locate XML for entity:', entityName, 'assetType:', assetType, 'relativePath:', relativePath);
                continue;
            }

            const codeContentRaw = await fs.readFile(codeFilePath, 'utf8');
            const codeContent = codeContentRaw.replace(/\r\n/g, '\n').replace(/^\s+|\s+$/g, '') + '\n';
            let xmlContent = await fs.readFile(actualXmlPath, 'utf8');

            let modified = false;
            const ext = path.extname(fileName);
            const serviceName = path.basename(fileName, ext);

            if (['Things', 'ThingShapes', 'ThingTemplates'].includes(assetType)) {
                // Regex replace
                const escapedServiceName = serviceName.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&');
                const regexStr = `(<ServiceImplementation[^>]*name=["']${escapedServiceName}["'][^>]*>[\\s\\S]*?<code>)([\\s\\S]*?)(<\\/code>)`;
                const svcRegex = new RegExp(regexStr);

                if (svcRegex.test(xmlContent)) {
                    xmlContent = xmlContent.replace(svcRegex, `$1\n<![CDATA[\n${codeContent}]]>\n$3`);
                    modified = true;
                } else {
                    // Also try <sql>...</sql> for sql files
                    if (ext === '.sql') {
                        const sqlRegexStr = `(<ServiceImplementation[^>]*name=["']${escapedServiceName}["'][^>]*>[\\s\\S]*?<sql>)([\\s\\S]*?)(<\\/sql>)`;
                        const sqlRegex = new RegExp(sqlRegexStr);
                        if (sqlRegex.test(xmlContent)) {
                            xmlContent = xmlContent.replace(sqlRegex, `$1\n<![CDATA[\n${codeContent}]]>\n$3`);
                            modified = true;
                        }
                    }
                }
            } else if (assetType === 'Mashups') {
                const mashupRegex = /(<mashupContent[^>]*>\s*<!\[CDATA\[)([\s\S]*?)(\]\]>\s*<\/mashupContent>)/;
                const match = xmlContent.match(mashupRegex);
                if (match) {
                    try {
                        const mashupData = JSON.parse(match[2].trim());
                        let jsonModified = false;

                        if (fileName === 'stylesheet.css') {
                            mashupData.CustomMashupCss = codeContentRaw; // keep original whitespace and tabs for CSS if possible
                            jsonModified = true;
                        } else if (ext === '.js' || ext === '.html') {
                            const lookupName = serviceName;
                            if (mashupData.UI && mashupData.UI.Widgets) {
                                const allWidgets = flattenWidgets(mashupData.UI);
                                // Match by DisplayName first (expression/validator), then by Id (htmltextarea)
                                const targetWidget = allWidgets.find(w => w.Properties && (
                                    w.Properties.DisplayName === lookupName || w.Properties.Id === lookupName
                                ));
                                if (targetWidget) {
                                    if (ext === '.js') {
                                        targetWidget.Properties.Expression = codeContentRaw;
                                        jsonModified = true;
                                    } else if (ext === '.html') {
                                        targetWidget.Properties.Text = codeContentRaw;
                                        jsonModified = true;
                                    }
                                }
                            }
                        }

                        if (jsonModified) {
                            const newMashupJson = JSON.stringify(mashupData, null, 2);
                            xmlContent = xmlContent.replace(mashupRegex, `$1\n${newMashupJson}\n$3`);
                            modified = true;
                        }
                    } catch (e) {
                        console.error(`Failed to parse/update mashupContent for embed in ${actualXmlPath}`, e);
                    }
                }
            }

            if (modified) {
                await fs.writeFile(actualXmlPath, xmlContent, 'utf8');
                changes.push({
                    xml: path.relative(THINGWORX_DIR, actualXmlPath).replace(/\\/g, '/'),
                    code: codeFilePath,
                    service: serviceName
                });
                console.log(`Embedded ${relativePath} -> ${path.basename(actualXmlPath)}`);
                vLog('Updated XML path:', actualXmlPath);
            }
        }

        if (changes.length > 0) {
            await fs.writeFile(path.join(codeDir, 'embed-report.json'), JSON.stringify(reportObj, null, 2), 'utf8');
            console.log(`Generated report: ${path.join(codeDir, 'embed-report.json')}`);
            vLog('Wrote embed-report:', path.join(codeDir, 'embed-report.json'));
        }
    }
}

gulp.task('extract-services', extractServicesTask);
gulp.task('embed-services', embedServicesTask);
